apiVersion: v1
kind: Service
metadata:
  name: redis-cluster  # Service name for Redis Cluster
spec:
  ports:
  - port: 6379  # Port 6379 for Redis
    targetPort: 6379  # Forwarding to the container's Redis port
  clusterIP: None  # Headless service, no single IP is assigned
  selector:
    app: redis-cluster  # Selects Redis Cluster pods for traffic routing
